on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - 'v**'

name: End to End Tests
jobs:
  e2e:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        globalnet: ['', 'globalnet']
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Reclaim free space!
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          df -h
          free -h

      - name: Run E2E deployment and tests
        run: |
          make e2e using="${{ matrix.globalnet }}"

      - name: Post Mortem
        if: failure()
        run: |
          df -h
          free -h
          make post-mortem
