---
name: Release the Target Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Debug Action
        uses: hmarr/debug-action@v1.0.0

